sudo: true
notifications:
  email: false

language: python
python:
  -  "2.7"

before_install:
  - sudo apt-get update

git:
  depth: 1

install:
  - sudo pip install CssefClient/.
  - sudo pip install CssefServer/.
  - sudo pip install nose
  
script:
  - nosetests CssefClient/.
  - nosetests CssefServer/.
