sudo: false
notifications:
  email: false

language: python
python:
  -  "2.7"

git:
  depth: 1
# command to install dependencies
install:
  - pip install CssefClient/.
  - pip install CssefServer/.
  - pip install nose
script:
  - nosetests --tests=CssefServer