sudo: true
notifications:
  email: false

language: python
python:
  -  "2.7"

git:
  depth: 1
# command to install dependencies
install:
  - sudo pip install CssefClient/.
  - sudo pip install CssefServer/.
  - sudo pip install nose
script:
  - ./pre-commit.sh --no-virtual-env
